### ISSUE TITLE
Add libglew-dev to list of dependencies?

### ISSUE THREAD

**Issue by Germanunkol** [gklingler/QOgreWidget#1]
Hi,

On Linux (Ubuntu 14.04) I needed an additional library, which wasn't installed and wasn't mentioned in the README:
libglew-dev
Maybe you want to add that to the dependencies?

Great work on this!
I got the demo compiled within minutes - I wasn't expecting that.

Thanks!

**Comment by gklingler** [comment]
thanks for reporting - added "GLEW" as a required dependency: ac3eeeffd028c98dd4e7fb16fdd47fff508736d9
